version: '3'
services:
  web:
    image: php:7.4-apache
    ports:
      - "8888:80"
    
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: example_password
      MYSQL_DATABASE: mydatabase